#server:
#  port: 8888
#spring:
#  application:
#    name: faichuis-gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          lower-case-service-id: true
#          enabled: true
#      routes:
#        - id: faichuis-authcenter
#          uri: lb://faichuis-authcenter
#          predicates:
#            - Path=/oauth/**
#        - id: faichuis-member
#          uri: lb://faichuis-member
#          predicates:
#            - Path=/sso/**,/member/**
#        - id: faichuisl-order
#          uri: lb://faichuis-order
#          predicates:
#            - Path=/cart/**,/order/**
#        - id: faichuis-product
#          uri: lb://faichuis-product
#          predicates:
#            - Path=/pms/**
#        - id: faichuis-coupons
#          uri: lb://faichuis-coupons
#          predicates:
#            - Path=/coupon/**
##    nacos:
##      discovery:
##        server-addr: 192.168.38.100:8848
#
#management: #开启SpringBoot Admin的监控
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always
#logging:
#  level:
#    org.springframework.cloud.gateway: debug
#
#tuling:
#  gateway:
#    shouldSkipUrls:
#      - /oauth/**
#      - /sso/**
